import { IoBoat, IoFish } from "react-icons/io5";
import { GiSpeedBoat, GiBoatEngine, GiDigitalTrace } from "react-icons/gi";
import { FaTools, FaTrailer } from "react-icons/fa";

export const categories = [
  { eu: "lodki", bg: "Лодки", Icon: IoBoat },
  { eu: "djetove", bg: "Джетове", Icon: GiSpeedBoat },
  { eu: "elektronika", bg: "Морска eлектроника", Icon: GiDigitalTrace },
  { eu: "dvigateli", bg: "Двигатели", Icon: GiBoatEngine },
  { eu: "kolesari", bg: "Колесари", Icon: FaTrailer },
  { eu: "ribolov", bg: "Риболов", Icon: IoFish },
  { eu: "chasti", bg: "Части", Icon: FaTools },
];

export const fieldConfigs = {
  lodki: {
    brands: ["Yamaha", "Mercury", "Honda", "Suzuki", "Bayliner", "Sea Ray"],
    models: ["Sport", "Fishing", "Cruiser", "Yacht"],
    hasYear: true,
    hasPrice: true,
    hasLength: true,
    hasCondition: true,
  },
  djetove: {
    brands: ["Sea-Doo", "Yamaha", "Kawasaki", "Honda"],
    models: ["RXT", "GTX", "Spark", "VX"],
    hasYear: true,
    hasPrice: true,
    hasHours: true,
    hasCondition: true,
  },
  elektronika: {
    brands: ["Garmin", "Lowrance", "Raymarine", "Simrad", "Humminbird"],
    categories: ["GPS", "Сонар", "Радар", "VHF Радио", "AIS"],
    hasPrice: true,
    hasCondition: true,
  },
  dvigateli: {
    brands: ["Mercury", "Yamaha", "Honda", "Suzuki", "Tohatsu", "Evinrude"],
    horsepower: true,
    hasYear: true,
    hasPrice: true,
    hasHours: true,
    hasCondition: true,
  },
  kolesari: {
    brands: ["SBS", "Harbeck", "Satellite", "Tema"],
    maxWeight: true,
    hasYear: true,
    hasPrice: true,
    hasCondition: true,
  },
  ribolov: {
    categories: ["Въдици", "Макари", "Примамки", "Сонари", "Аксесоари"],
    brands: ["Shimano", "Daiwa", "Penn", "Abu Garcia"],
    hasPrice: true,
    hasCondition: true,
  },
  chasti: {
    partType: ["Двигател", "Електроника", "Корпус", "Интериор", "Палуба"],
    brands: ["Universal", "OEM", "Aftermarket"],
    hasPrice: true,
    hasCondition: true,
  },
};

export const formatDate = (date) => {
  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();

  return `${hours}:${minutes} часа на ${day}.${month}.${year}`;
};

export const data = [
  {
    id: 1,
    name: "СОНАР HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    condition: "Употребяван",
    screenSize: '5"',
    horsepower: 200,
    maxLoadCapacity: 10,
    length: 10,
    width: 5,
    fuel: 2,
    features: [
      "FISH REVEAL",
      "DOWN SCAN",
      "SIDE SCAN",
      "IPS ЕКРАН",
      "HDMI ПОРТ",
      "ETHERNET",
    ],
    description:
      "Сонара е чисто нов купуван от Булстар, не е използван и вече не е в гаранция. 2017 година е, не се използва. Комплект с кабел и сонар",
    createBy: 101,
    createDate: new Date(),
    price: 350,
    promo: true,
  },
  {
    id: 2,
    name: "LOWRANCE HDS-7 LIVE",
    brand: "LOWRANCE",
    model: "HDS-7 LIVE",
    place: "София",
    image: "/product-2.png",
    year: 2020,
    condition: "Нов",
    screenSize: '7"',
    horsepower: 250,
    maxLoadCapacity: 15,
    length: 12,
    width: 6,
    fuel: 3,
    features: [
      "ACTIVE IMAGING",
      "LIVE SONAR",
      "SIDE SCAN",
      "TOUCH SCREEN",
      "WIFI",
      "BLUETOOTH",
    ],
    description:
      "Професионален сонар с най-новите технологии. Перфектен за риболов.",
    createBy: 101,
    createDate: new Date(),
    price: 1250,
    promo: true,
  },
  {
    id: 3,
    name: "GARMIN ECHOMAP UHD 93SV",
    brand: "GARMIN",
    model: "ECHOMAP UHD",
    place: "Варна",
    image: "/product-3.png",
    year: 2021,
    condition: "Употребяван",
    screenSize: '9"',
    horsepower: 300,
    maxLoadCapacity: 20,
    length: 15,
    width: 7,
    fuel: 4,
    features: [
      "ULTRA HIGH-DEF",
      "CLEARVU",
      "SIDEVU",
      "GPS",
      "QUICKDRAW",
      "WIFI",
    ],
    description:
      "Топ модел с кристално ясна картина. Използван само един сезон.",
    createBy: 101,
    createDate: new Date(),
    price: 1800,
    promo: true,
  },
  {
    id: 4,
    name: "HUMMINBIRD HELIX 5 CHIRP",
    brand: "HUMMINBIRD",
    model: "HELIX 5",
    place: "Пловдив",
    image: "/product-1.png",
    year: 2019,
    condition: "Употребяван",
    screenSize: '5"',
    horsepower: 150,
    maxLoadCapacity: 8,
    length: 8,
    width: 4,
    fuel: 2,
    features: [
      "CHIRP SONAR",
      "DOWN IMAGING",
      "GPS",
      "AUTOCHAR LIVE",
      "MICROSD SLOT",
    ],
    description: "Отличен бюджетен вариант с всички основни функции.",
    createBy: 101,
    createDate: new Date(),
    price: 450,
    promo: true,
  },
  {
    id: 5,
    name: "RAYMARINE AXIOM 12 RV",
    brand: "RAYMARINE",
    model: "AXIOM",
    place: "Русе",
    image: "/product-1.png",
    year: 2022,
    condition: "Нов",
    screenSize: '12"',
    horsepower: 350,
    maxLoadCapacity: 25,
    length: 18,
    width: 8,
    fuel: 5,
    features: [
      "REALVISION 3D",
      "LIGHTHOUSE OS",
      "WIFI",
      "BLUETOOTH",
      "HDMI",
      "NETWORK",
    ],
    description: "Професионална навигационна система с 3D сонар технология.",
    createBy: 101,
    createDate: new Date(),
    price: 3500,
    promo: false,
  },
  {
    id: 6,
    name: "SIMRAD NSS EVO3",
    brand: "SIMRAD",
    model: "NSS EVO3",
    place: "Бургас",
    image: "/product-2.png",
    year: 2018,
    condition: "Употребяван",
    screenSize: '7"',
    horsepower: 200,
    maxLoadCapacity: 12,
    length: 10,
    width: 5,
    fuel: 3,
    features: [
      "FORWARDSCAN",
      "STRUCTURESCAN",
      "BROADBAND RADAR",
      "WIFI",
      "NMEA 2000",
    ],
    description: "Мултифункционален дисплей с радар съвместимост.",
    createBy: 101,
    createDate: new Date(),
    price: 980,
    promo: false,
  },
  {
    id: 7,
    name: "LOWRANCE HOOK REVEAL 5",
    brand: "LOWRANCE",
    model: "HOOK REVEAL",
    place: "Стара Загора",
    image: "/product-2.png",
    year: 2021,
    condition: "Нов",
    screenSize: '5"',
    horsepower: 100,
    maxLoadCapacity: 5,
    length: 6,
    width: 3,
    fuel: 1,
    features: ["FISH REVEAL", "DOWNSCAN", "GPS PLOTTER", "GENESIS LIVE"],
    description: "Компактен и достъпен сонар за малки лодки.",
    createBy: 101,
    createDate: new Date(),
    price: 380,
    promo: false,
  },
  {
    id: 8,
    name: "GARMIN STRIKER VIVID 7CV",
    brand: "GARMIN",
    model: "STRIKER VIVID",
    place: "Велико Търново",
    image: "/product-3.png",
    year: 2020,
    condition: "Употребяван",
    screenSize: '7"',
    horsepower: 180,
    maxLoadCapacity: 10,
    length: 9,
    width: 4.5,
    fuel: 2,
    features: ["VIVID COLOR", "CLEARVU", "GPS", "QUICKDRAW", "WAYPOINT MAP"],
    description: "Цветен дисплей с високо качество на изображението.",
    createBy: 101,
    createDate: new Date(),
    price: 520,
    promo: false,
  },
  {
    id: 9,
    name: "HUMMINBIRD SOLIX 10",
    brand: "HUMMINBIRD",
    model: "SOLIX",
    place: "Плевен",
    image: "/product-1.png",
    year: 2019,
    condition: "Употребяван",
    screenSize: '10"',
    horsepower: 280,
    maxLoadCapacity: 18,
    length: 14,
    width: 6.5,
    fuel: 4,
    features: [
      "MEGA IMAGING",
      "DUAL SPECTRUM",
      "AUTOCHART",
      "BLUETOOTH",
      "ETHERNET",
      "WIFI",
    ],
    description: "Премиум модел с мега имиджинг технология.",
    createBy: 101,
    createDate: new Date(),
    price: 1650,
    promo: false,
  },
  {
    id: 10,
    name: "RAYMARINE ELEMENT 7 HV",
    brand: "RAYMARINE",
    model: "ELEMENT",
    place: "София",
    image: "/product-1.png",
    year: 2021,
    condition: "Нов",
    screenSize: '7"',
    horsepower: 220,
    maxLoadCapacity: 14,
    length: 11,
    width: 5.5,
    fuel: 3,
    features: ["HYPERVISION", "3D SONAR", "LIGHTHOUSE SPORT", "WIFI", "GPS"],
    description: "Лесен за използване с интуитивен интерфейс.",
    createBy: 101,
    createDate: new Date(),
    price: 890,
    promo: false,
  },
  {
    id: 11,
    name: "SIMRAD GO7 XSE",
    brand: "SIMRAD",
    model: "GO7 XSE",
    place: "Варна",
    image: "/product-3.png",
    year: 2018,
    condition: "Употребяван",
    screenSize: '7"',
    horsepower: 190,
    maxLoadCapacity: 11,
    length: 10,
    width: 5,
    fuel: 2.5,
    features: ["TOTALSCAN", "C-MAP", "WIFI", "NMEA 2000", "BROADBAND SOUNDER"],
    description: "Мултитъч дисплей с всички необходими функции.",
    createBy: 101,
    createDate: new Date(),
    price: 750,
    promo: false,
  },
  {
    id: 12,
    name: "LOWRANCE HDS-9 CARBON",
    brand: "LOWRANCE",
    model: "HDS CARBON",
    place: "Добрич",
    image: "/product-3.png",
    year: 2017,
    condition: "Употребяван",
    screenSize: '9"',
    horsepower: 260,
    maxLoadCapacity: 16,
    length: 13,
    width: 6,
    fuel: 3.5,
    features: [
      "STRUCTURESCAN 3D",
      "CHIRP",
      "WIRELESS",
      "DUAL CORE",
      "SOLARMAX HD",
    ],
    description: "Професионален модел с карбонов корпус.",
    createBy: 101,
    createDate: new Date(),
    price: 1100,
    promo: false,
  },
  {
    id: 13,
    name: "GARMIN GPSMAP 1222XSV",
    brand: "GARMIN",
    model: "GPSMAP",
    place: "Шумен",
    image: "/product-3.png",
    year: 2020,
    condition: "Нов",
    screenSize: '12"',
    horsepower: 320,
    maxLoadCapacity: 22,
    length: 16,
    width: 7.5,
    fuel: 4.5,
    features: [
      "KEYED ASSIST",
      "ONEHELM",
      "ACTIVECAPTAIN",
      "PANOPTIX",
      "NETWORK CAPABLE",
    ],
    description: "Голям дисплей за професионална навигация.",
    createBy: 101,
    createDate: new Date(),
    price: 2800,
    promo: false,
  },
  {
    id: 14,
    name: "HUMMINBIRD HELIX 7 CHIRP MSI",
    brand: "HUMMINBIRD",
    model: "HELIX 7",
    place: "Хасково",
    image: "/product-1.png",
    year: 2019,
    condition: "Употребяван",
    screenSize: '7"',
    horsepower: 210,
    maxLoadCapacity: 13,
    length: 11,
    width: 5.2,
    fuel: 3,
    features: ["MEGA SIDE IMAGING", "CHIRP", "GPS G3", "ETHERNET", "BLUETOOTH"],
    description: "Модел с мега страничен имиджинг.",
    createBy: 101,
    createDate: new Date(),
    price: 780,
    promo: false,
  },
  {
    id: 15,
    name: "RAYMARINE AXIOM PRO 9",
    brand: "RAYMARINE",
    model: "AXIOM PRO",
    place: "Благоевград",
    image: "/product-2.png",
    year: 2021,
    condition: "Нов",
    screenSize: '9"',
    horsepower: 270,
    maxLoadCapacity: 17,
    length: 12.5,
    width: 6,
    fuel: 3.5,
    features: [
      "CHIRP CONICAL",
      "REALVISION 3D",
      "1KW SONAR",
      "HYBRID TOUCH",
      "QUADCORE",
    ],
    description: "Професионален модел с хибриден тъчскрийн.",
    createBy: 101,
    createDate: new Date(),
    price: 2200,
    promo: false,
  },
  {
    id: 16,
    name: "SIMRAD NSX 3009",
    brand: "SIMRAD",
    model: "NSX",
    place: "Пазарджик",
    image: "/product-2.png",
    year: 2022,
    condition: "Нов",
    screenSize: '9"',
    horsepower: 240,
    maxLoadCapacity: 15,
    length: 11.5,
    width: 5.8,
    fuel: 3.2,
    features: [
      "ACTIVE IMAGING HD",
      "C-MAP DISCOVER X",
      "SIMRAD APP",
      "HALO RADAR",
      "WIFI 6",
    ],
    description: "Най-новият модел с активен HD имиджинг.",
    createBy: 101,
    createDate: new Date(),
    price: 1950,
    promo: false,
  },
  {
    id: 17,
    name: "LOWRANCE ELITE FS 9",
    brand: "LOWRANCE",
    model: "ELITE FS",
    place: "Сливен",
    image: "/product-2.png",
    year: 2021,
    condition: "Употребяван",
    screenSize: '9"',
    horsepower: 230,
    maxLoadCapacity: 14,
    length: 11,
    width: 5.5,
    fuel: 3,
    features: [
      "ACTIVETARGET",
      "C-MAP CONTOUR+",
      "WIRELESS",
      "PRELOADED MAPPING",
      "FISHREVEAL",
    ],
    description: "Модел с ActiveTarget live сонар съвместимост.",
    createBy: 101,
    createDate: new Date(),
    price: 1320,
    promo: false,
  },
];

export const user = {
  id: 101,
  name: "Цанко Йорданов",
  email: "K0g9Y@example.com",
  phone: "0888888888",
  password: "12345678",
  confirmPassword: "12345678",
};
