import { IoBoat, IoFish } from "react-icons/io5";
import { GiSpeedBoat, GiBoatEngine, GiDigitalTrace } from "react-icons/gi";
import { FaTools, FaTrailer } from "react-icons/fa";

export const categories = [
  { eu: "lodki", bg: "Лодки", Icon: IoBoat },
  { eu: "djetove", bg: "Джетове", Icon: GiSpeedBoat },
  { eu: "elektronika", bg: "Морска eлектроника", Icon: GiDigitalTrace },
  { eu: "dvigateli", bg: "Двигатели", Icon: GiBoatEngine },
  { eu: "kolesari", bg: "Колесари", Icon: FaTrailer },
  { eu: "ribolov", bg: "Риболов", Icon: IoFish },
  { eu: "chasti", bg: "Части", Icon: FaTools },
];

export const fieldConfigs = {
  lodki: {
    brands: ["Yamaha", "Mercury", "Honda", "Suzuki", "Bayliner", "Sea Ray"],
    models: ["Sport", "Fishing", "Cruiser", "Yacht"],
    hasYear: true,
    hasPrice: true,
    hasLength: true,
    hasCondition: true,
  },
  djetove: {
    brands: ["Sea-Doo", "Yamaha", "Kawasaki", "Honda"],
    models: ["RXT", "GTX", "Spark", "VX"],
    hasYear: true,
    hasPrice: true,
    hasHours: true,
    hasCondition: true,
  },
  elektronika: {
    brands: ["Garmin", "Lowrance", "Raymarine", "Simrad", "Humminbird"],
    categories: ["GPS", "Сонар", "Радар", "VHF Радио", "AIS"],
    hasPrice: true,
    hasCondition: true,
  },
  dvigateli: {
    brands: ["Mercury", "Yamaha", "Honda", "Suzuki", "Tohatsu", "Evinrude"],
    horsepower: true,
    hasYear: true,
    hasPrice: true,
    hasHours: true,
    hasCondition: true,
  },
  kolesari: {
    brands: ["SBS", "Harbeck", "Satellite", "Tema"],
    maxWeight: true,
    hasYear: true,
    hasPrice: true,
    hasCondition: true,
  },
  ribolov: {
    categories: ["Въдици", "Макари", "Примамки", "Сонари", "Аксесоари"],
    brands: ["Shimano", "Daiwa", "Penn", "Abu Garcia"],
    hasPrice: true,
    hasCondition: true,
  },
  chasti: {
    partType: ["Двигател", "Електроника", "Корпус", "Интериор", "Палуба"],
    brands: ["Universal", "OEM", "Aftermarket"],
    hasPrice: true,
    hasCondition: true,
  },
};

export const formatDate = (date) => {
  const hours = date.getHours().toString().padStart(2, "0");
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const day = date.getDate().toString().padStart(2, "0");
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const year = date.getFullYear();

  return `${hours}:${minutes} часа на ${day}.${month}.${year}`;
};

export const data = [
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
    promo: true,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
    promo: true,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
    promo: true,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
    promo: true,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
  {
    name: "COHAP HDS PRO SIMRAD 2017",
    brand: "SIMRAD",
    model: "CRUISE",
    place: "Бургас",
    image: "/product-1.png",
    year: 2017,
    createDate: new Date(),
    price: 350,
  },
];
